language: python
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - ipython kernel install --name "python3" --user
# command to run tests
script:
  - pytest -s tests/*
