language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest -s tests/*
